#!/bin/sh
set -e

if [ ! "$CRON_WORKER_RESTART" = "True" ];then
  exit 0
fi

# find nassl worker and restart the container(s)
docker ps --filter label=com.docker.compose.service=worker-nassl --filter label=com.docker.compose.project="$COMPOSE_PROJECT" --quiet |  xargs -n1 --no-run-if-empty -I% sh -c 'docker restart %; sleep 30'
