services:
  webserver:
    build:
      context: ..
      dockerfile: docker/webserver.Dockerfile

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: app
      platforms:
        # required because current version of nassl cannot be compile for ARM (eg: Apple Silicon)
        - "linux/amd64"

  db-migrate:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: app
      platforms:
        # required because current version of nassl cannot be compile for ARM (eg: Apple Silicon)
        - "linux/amd64"

  worker: &worker
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: app
      platforms:
        # required because current version of nassl cannot be compile for ARM (eg: Apple Silicon)
        - "linux/amd64"

  worker-nassl:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: app
      platforms:
        # required because current version of nassl cannot be compile for ARM (eg: Apple Silicon)
        - "linux/amd64"

  worker-slow:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: app
      platforms:
        # required because current version of nassl cannot be compile for ARM (eg: Apple Silicon)
        - "linux/amd64"

  beat:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: app
      platforms:
        # required because current version of nassl cannot be compile for ARM (eg: Apple Silicon)
        - "linux/amd64"

  unbound:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: unbound
      platforms:
        # required because current version of nassl cannot be compile for ARM (eg: Apple Silicon)
        - "linux/amd64"

  resolver-validating:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: unbound
      platforms:
        # required because current version of nassl cannot be compile for ARM (eg: Apple Silicon)
        - "linux/amd64"

  cron:
    build:
      context: ..
      dockerfile: docker/util.Dockerfile

  cron-docker:
    build:
      context: ..
      dockerfile: docker/util.Dockerfile

  grafana:
    build:
      context: ..
      dockerfile: docker/grafana.Dockerfile

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: linttest
      args:
        RELEASE: 0.0.0-dev0
      platforms:
        # required because current version of nassl cannot be compile for ARM (eg: Apple Silicon)
        - "linux/amd64"

  test-runner:
    build:
      context: ..
      dockerfile: docker/test-runner.Dockerfile

  test-runner-development-environment:
    build:
      context: ..
      dockerfile: docker/test-runner.Dockerfile

  test-runner-live:
    build:
      context: ..
      dockerfile: docker/test-runner.Dockerfile

  tools:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: linttest
      args:
        RELEASE: 0.0.0-dev0
      platforms:
        # required because current version of nassl cannot be compile for ARM (eg: Apple Silicon)
        - "linux/amd64"

  mock-resolver:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: unbound
      platforms:
        # required because current version of nassl cannot be compile for ARM (eg: Apple Silicon)
        - "linux/amd64"
