services:
  # test runner intended to run live tests against targets on public internet
  test-runner-development-environment:
    platform: linux/amd64
    image: ${DOCKER_IMAGE_TEST_RUNNER:-${DOCKER_REGISTRY:-ghcr.io/internetstandards}/test-runner:$RELEASE}
    environment:
      - APP_URLS
      - BATCH_API_AUTH
      - TEST_DOMAINS
      - TEST_EMAILS
    networks:
      live-tests:
    # required for linux hosts as host.docker.internal does not resolve
    extra_hosts:
      - "host-gateway:host-gateway"
    volumes:
      - ../:/source
      # make docker available inside the container
      - /var/run/docker.sock:/var/run/docker.sock
    profiles:
      # adding a profile makes sure this service is not started during `make up env=develop`
      - run-tests

networks:
  live-tests:
    # required to enable IPv6 on Docker Desktop runtime
    enable_ipv6: true
    driver: bridge
    driver_opts:
      # required to enable IPv6 on Colima Docker runtime
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        # configure a private IPv6 subnet
        # https://docs.docker.com/config/daemon/ipv6/#create-an-ipv6-network
        - subnet: fd00:44::/80
