services:
  # test runner for integration tests in isolated environment
  test-runner:
    image: $DOCKER_IMAGE_TEST_RUNNER
    build:
      context: ..
      dockerfile: docker/Dockerfile.test-runner
    # don't run anything, just make this container available to run tests in on demand
    command: python3 -m pytest -v integration_tests/integration/
    networks:
      public-internet:
      internal:
    volumes:
      - ../:/source/
      # make docker available inside the container
      - /var/run/docker.sock:/var/run/docker.sock
    profiles:
      - run-tests
    dns: $IPV4_IP_RESOLVER_INTERNAL
    depends_on:
      webserver:
        condition: service_started
      app:
        condition: service_healthy
      worker:
        condition: service_started
      beat:
        condition: service_started
      test-target:
        condition: service_healthy
      mail-test-target:
        condition: service_started
      resolver:
        condition: service_started
      # not required for running the test suite, but useful to access the test environment
      port-expose:
        condition: service_started
