# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-23 22:33
from __future__ import unicode_literals

import interface.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0006_mailtestauth_dmarc_record_org_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtestdnssec',
            name='mx_status',
            field=enumfields.fields.EnumIntegerField(enum=checks.models.MxStatus, null=True),
        ),
        migrations.AddField(
            model_name='mailtestipv6',
            name='mx_status',
            field=enumfields.fields.EnumIntegerField(enum=checks.models.MxStatus, null=True),
        ),
        migrations.AddField(
            model_name='mailtesttls',
            name='mx_status',
            field=enumfields.fields.EnumIntegerField(enum=checks.models.MxStatus, null=True),
        ),
    ]
