{
 "title": "Batch",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Version",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "internetnl_version_info", "legendFormat": "__auto" }
   ]
  },
  { "title": "Tasks/Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (    increase(      celery_task_succeeded_total{        job=~\"celery|celery_exporter\",      }[$__rate_interval]    ))\n",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_failed_total{\n        job=~\"celery|celery_exporter\",\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_sent_total{\n        job=~\"celery|celery_exporter\",\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Put on queue"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_received_total{\n        job=~\"celery|celery_exporter\",\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Picked up from queue"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_retried_total{\n        job=~\"celery|celery_exporter\",\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Retried"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_rejected_total{\n        job=~\"celery|celery_exporter\",\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Rejected"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_revoked_total{\n        job=~\"celery|celery_exporter\",\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Revoked"
    }
   ]
  },
  {
   "title": "Individual task completion rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "x/s" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(celery_task_succeeded_total[$__rate_interval])) > 0\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Active tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "celery_worker_tasks_active{job=~\"celery|celery_exporter\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Task runtimes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(celery_task_runtime_sum{job=~\"celery|celery_exporter\"}[10m])) / sum by (name) (rate(celery_task_runtime_count{job=~\"celery|celery_exporter\"}[10m])) > 0\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum (\n  celery_queue_length{\n    job=~\"celery|celery_exporter\",\n  }\n) by (job, queue_name)\n",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "System CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{}[$__rate_interval])))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{}[$__rate_interval])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{}[$__rate_interval])))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=~\".*irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{}[$__rate_interval])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{}[$__rate_interval])))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{}[$__rate_interval])))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Worker CPU usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(docker_container_cpu_seconds_total{name=~\"internetnl-[a-z]+-worker.*\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "System memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes{}", "legendFormat": "RAM Total" },
    {
     "expr": "node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - (node_memory_Cached_bytes{} + node_memory_Buffers_bytes{} + node_memory_SReclaimable_bytes{})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{} + node_memory_Buffers_bytes{} + node_memory_SReclaimable_bytes{}",
     "legendFormat": "RAM Cache + Buffer"
    },
    { "expr": "node_memory_MemFree_bytes{}", "legendFormat": "RAM Free" },
    {
     "expr": "(node_memory_SwapTotal_bytes{} - node_memory_SwapFree_bytes{})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Worker memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "docker_container_memory_usage_bytes{name=~\"internetnl-[a-z]+-worker.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "OOM kills",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(node_vmstat_oom_kill[$__rate_interval])",
     "legendFormat": "OOM kills"
    }
   ]
  },
  { "title": "Files/sockets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Sockstat TCP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_sockstat_TCP_alloc", "legendFormat": "TCP_alloc - Allocated sockets" },
    {
     "expr": "node_sockstat_TCP_inuse",
     "legendFormat": "TCP_inuse - Tcp sockets currently in use"
    },
    { "expr": "node_sockstat_TCP_orphan", "legendFormat": "TCP_orphan - Orphan sockets" },
    { "expr": "node_sockstat_TCP_tw", "legendFormat": "TCP_tw - Sockets waiting close" }
   ]
  }
 ]
}