{
 "title": "Celery / Tasks / Overview",
 "description": "A dashboard that monitors Celery. It is created using the Celery-mixin for the the (Celery-exporter)[https://github.com/danihodovic/celery-exporter]",
 "tags": [
  "celery",
  "celery-mixin"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(celery_worker_up, job)"
   },
   {
    "name": "queue_name",
    "label": "Queue Name",
    "query": "label_values(celery_task_received_total{job=\"$job\", name!~\"None\"}, queue_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  celery_worker_up{\n    job=\"$job\",\n    job=~\"celery|celery_exporter\"\n  } == 1\n)\n"
    }
   ]
  },
  {
   "title": "Tasks Active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n  celery_worker_tasks_active{\n    job=\"$job\",\n    job=~\"celery|celery_exporter\"\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Tasks received by workers [1w]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      celery_task_received_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[1w]\n    )\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Tasks Success Rate [1w]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      celery_task_succeeded_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[1w]\n    )\n  )\n)\n/(sum(\n  round(\n    increase(\n      celery_task_succeeded_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[1w]\n    )\n  )\n)\n+sum(\n  round(\n    increase(\n      celery_task_failed_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[1w]\n    )\n  )\n)\n)\n"
    }
   ]
  },
  {
   "title": "Average Runtime for Tasks [1w]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    celery_task_runtime_sum{\n      job=\"$job\",\n      job=~\"celery|celery_exporter\",\n      queue_name=~\"$queue_name\"\n    }[1w]\n  )\n)\n/\nsum(\n  rate(\n    celery_task_runtime_count{\n      job=\"$job\",\n      job=~\"celery|celery_exporter\",\n      queue_name=~\"$queue_name\"\n    }[1w]\n  )\n) > 0\n"
    }
   ]
  },
  {
   "title": "Top Failed Tasks [1w]",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "round(\n  sum (\n    increase(\n      celery_task_failed_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[1w]\n    ) > 0\n  )  by (name)\n)\n"
    }
   ]
  },
  {
   "title": "Top Task Exceptions [1w]",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "round(\n  sum (\n    increase(\n      celery_task_failed_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[1w]\n    )\n  ) by (exception) > 0\n)\n"
    }
   ]
  },
  {
   "title": "Top Average Task Runtime [1w]",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "sum (\n  rate(\n    celery_task_runtime_sum{\n      job=\"$job\",\n      job=~\"celery|celery_exporter\",\n      queue_name=~\"$queue_name\"\n    }[1w]\n  )\n) by(name)\n/\nsum (\n  rate(\n    celery_task_runtime_count{\n      job=\"$job\",\n      job=~\"celery|celery_exporter\",\n      queue_name=~\"$queue_name\"\n    }[1w]\n  )\n) by (name) > 0\n"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queue Length",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (\n  celery_queue_length{\n    job=\"$job\",\n    job=~\"celery|celery_exporter\",\n    queue_name=~\"$queue_name\"\n  }\n) by (job, queue_name)\n",
     "legendFormat": "{{ queue_name }}"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Task Stats",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_succeeded_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (job)\n/(sum (\n  round(\n    increase(\n      celery_task_succeeded_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (job)\n+sum (\n  round(\n    increase(\n      celery_task_failed_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (job)\n) > -1\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_succeeded_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (job) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_failed_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (job) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_sent_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (job) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_received_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (job) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_rejected_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (job) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_retried_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (job) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_revoked_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (job) > 0\n"
    }
   ]
  },
  {
   "title": "Tasks completed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_succeeded_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_failed_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_sent_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_received_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Received"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_retried_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Retried"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_rejected_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Rejected"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_revoked_total{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Revoked"
    }
   ]
  },
  {
   "title": "Tasks Runtime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n  sum(\n    irate(\n      celery_task_runtime_bucket{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "50"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    irate(\n      celery_task_runtime_bucket{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum(\n    irate(\n      celery_task_runtime_bucket{\n        job=\"$job\",\n        job=~\"celery|celery_exporter\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "99"
    }
   ]
  }
 ]
}