# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 08:51
from __future__ import unicode_literals

import checks.models
import enumfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaintesttls',
            name='protocols_phase_out',
            field=checks.models.ListField(null=True),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='fs_phase_out',
            field=checks.models.ListField(null=True),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='zero_rtt_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='ocsp_stapling',
            field=enumfields.fields.EnumField(
                default=0, enum=checks.models.OcspStatus, max_length=10),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='zero_rtt',
            field=enumfields.fields.EnumField(
                default=0, enum=checks.models.ZeroRttStatus, max_length=10),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='ocsp_stapling_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='cert_pubkey_phase_out',
            field=checks.models.ListField(null=True),
        ),
        migrations.AddField(
    ]
