# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 08:51
from __future__ import unicode_literals

import checks.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaintesttls',
            name='protocols_phase_out',
            field=checks.models.ListField(null=True),
        ),
    ]
