# Generated by Django 1.11 on 2019-05-22 11:52

from django.db import migrations

import checks.models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domaintestappsecpriv",
            name="content_security_policy_values",
            field=checks.models.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name="domaintestappsecpriv",
            name="referrer_policy_values",
            field=checks.models.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name="domaintestappsecpriv",
            name="x_content_type_options_values",
            field=checks.models.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name="domaintestappsecpriv",
            name="x_frame_options_values",
            field=checks.models.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name="domaintestappsecpriv",
            name="x_xss_protection_values",
            field=checks.models.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name="domaintesttls",
            name="dane_records",
            field=checks.models.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name="domaintesttls",
            name="hsts_policies",
            field=checks.models.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name="mailtestauth",
            name="dmarc_record",
            field=checks.models.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name="mailtestauth",
            name="spf_record",
            field=checks.models.ListField(default=[]),
        ),
    ]
