# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-26 13:53
from __future__ import unicode_literals

import checks.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_upgrade_some_TextFields_to_ListFields'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaintesttls',
            name='cert_pubkey_phase_out',
            field=checks.models.ListField(null=True),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='ciphers_phase_out',
            field=checks.models.ListField(null=True),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='fs_phase_out',
            field=checks.models.ListField(null=True),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='ocsp_stapling',
            field=enumfields.fields.EnumField(default=0, enum=checks.models.OcspStatus, max_length=10),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='ocsp_stapling_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='protocols_phase_out',
            field=checks.models.ListField(null=True),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='zero_rtt',
            field=enumfields.fields.EnumField(default=0, enum=checks.models.ZeroRttStatus, max_length=10),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='zero_rtt_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='cipher_order',
            field=enumfields.fields.EnumField(default=0, enum=checks.models.CipherOrderStatus, max_length=10),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='cipher_order_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='cipher_order_violation',
            field=checks.models.ListField(null=True)
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='hash_func',
            field=enumfields.fields.EnumField(default=0, enum=checks.models.HashFuncStatus, max_length=10),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='hash_func_score',
            field=models.IntegerField(null=True),
        ),
    ]
