# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-10 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_domaintesttls_protocols_phase_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaintesttls',
            name='zero_rtt_score',
            field=models.IntegerField(null=True),
        ),
    ]
