# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-07 20:22
from __future__ import unicode_literals

import checks.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0003_summer'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrequest',
            name='report_technical_file',
            field=models.FileField(null=True, upload_to='batch_results/'),
        ),
        migrations.AlterField(
            model_name='mxdomain',
            name='mailtestipv6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mxdomains', to='checks.MailTestIpv6'),
        ),
        migrations.AlterField(
            model_name='mxdomain',
            name='v4_bad',
            field=checks.models.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name='mxdomain',
            name='v4_good',
            field=checks.models.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name='mxdomain',
            name='v6_bad',
            field=checks.models.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name='mxdomain',
            name='v6_good',
            field=checks.models.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name='nsdomain',
            name='domaintestipv6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nsdomains', to='checks.DomainTestIpv6'),
        ),
        migrations.AlterField(
            model_name='nsdomain',
            name='mailtestipv6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nsdomains', to='checks.MailTestIpv6'),
        ),
        migrations.AlterField(
            model_name='nsdomain',
            name='v4_bad',
            field=checks.models.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name='nsdomain',
            name='v4_good',
            field=checks.models.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name='nsdomain',
            name='v6_bad',
            field=checks.models.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name='nsdomain',
            name='v6_good',
            field=checks.models.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name='webdomain',
            name='domaintestipv6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webdomains', to='checks.DomainTestIpv6'),
        ),
        migrations.AlterField(
            model_name='webdomain',
            name='v4_bad',
            field=checks.models.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name='webdomain',
            name='v4_good',
            field=checks.models.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name='webdomain',
            name='v6_bad',
            field=checks.models.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name='webdomain',
            name='v6_good',
            field=checks.models.ListField(default=[]),
        ),
    ]
