# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-11 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0003_domaintesttls_zero_rtt_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaintesttls',
            name='ocsp_stapling',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='ocsp_stapling_score',
            field=models.IntegerField(null=True),
        ),
    ]
