# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-13 16:11
from __future__ import unicode_literals

import checks.models
from django.db import migrations, models
import enumfields.fields


def record_report_id_thresholds(apps, schema_editor):
    """
    Helper function to record the current report IDs so that we can hide them
    (redirect) when a new report presentation would break parsing/the design.

    ..note:: Needs to be copied and used in migration files to avoid code
             dependency when migrating.

    """
    app_name = 'checks'
    WebModel = apps.get_model(app_name, 'DomainTestReport')
    MailModel = apps.get_model(app_name, 'MailTestReport')
    AutoConfModel = apps.get_model(app_name, 'AutoConf')

    for model, op_name in [
            (WebModel, 'DATED_REPORT_ID_THRESHOLD_WEB'),
            (MailModel, 'DATED_REPORT_ID_THRESHOLD_MAIL')]:
        res = model.objects.order_by('-id')[:1]
        id = 0
        if res:
            id = res[0].id
        au = AutoConfModel(name=op_name, value=id)
        au.save()


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0004_APIv2__add_technical_file__reverse_lookup_names__remove_custom_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoConf',
            fields=[
                ('name', enumfields.fields.EnumField(enum=checks.models.AutoConfOption, max_length=255, primary_key=True, serialize=False)),
                ('value', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.RunPython(record_report_id_thresholds),
    ]
