# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-04 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0005_autoconf_db_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtestauth',
            name='dmarc_record_org_domain',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
