# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-04 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0006_mailtestauth_dmarc_record_org_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtestdnssec',
            name='has_null_mx',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailtestipv6',
            name='has_null_mx',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailtesttls',
            name='has_null_mx',
            field=models.BooleanField(default=False),
        ),
    ]
