# Generated by Django 1.11.23 on 2021-01-23 22:33

import enumfields.fields
from django.db import migrations

import checks.models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0006_mailtestauth_dmarc_record_org_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailtestdnssec",
            name="mx_status",
            field=enumfields.fields.EnumIntegerField(enum=checks.models.MxStatus, null=True),
        ),
        migrations.AddField(
            model_name="mailtestipv6",
            name="mx_status",
            field=enumfields.fields.EnumIntegerField(enum=checks.models.MxStatus, null=True),
        ),
        migrations.AddField(
            model_name="mailtesttls",
            name="mx_status",
            field=enumfields.fields.EnumIntegerField(enum=checks.models.MxStatus, null=True),
        ),
    ]
