# Generated by Django 3.2.12 on 2022-07-18 12:03

import checks.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0008_django_upgrade"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailTestRpki",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("domain", models.CharField(default="", max_length=255)),
                ("report", checks.models.ListField(default="")),
                ("mail_score", models.IntegerField(null=True)),
                ("ns_score", models.IntegerField(null=True)),
                ("score", models.IntegerField(null=True)),
                ("max_score", models.IntegerField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WebTestRpki",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("domain", models.CharField(default="", max_length=255)),
                ("report", checks.models.ListField(default="")),
                ("web_score", models.IntegerField(null=True)),
                ("ns_score", models.IntegerField(null=True)),
                ("score", models.IntegerField(null=True)),
                ("max_score", models.IntegerField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="batchmailtest",
            name="rpki_errors",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="batchmailtest",
            name="rpki_status",
            field=enumfields.fields.EnumIntegerField(default=0, enum=checks.models.BatchTestStatus),
        ),
        migrations.AddField(
            model_name="batchwebtest",
            name="rpki_errors",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="batchwebtest",
            name="rpki_status",
            field=enumfields.fields.EnumIntegerField(default=0, enum=checks.models.BatchTestStatus),
        ),
        migrations.CreateModel(
            name="RpkiWebHost",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("host", models.CharField(max_length=255)),
                ("score", models.IntegerField(null=True)),
                ("routing", checks.models.ListField(default={})),
                (
                    "webtestrpki",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhosts",
                        to="checks.webtestrpki",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RpkiNsHost",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("host", models.CharField(max_length=255)),
                ("score", models.IntegerField(null=True)),
                ("routing", checks.models.ListField(default={})),
                (
                    "mailtestrpki",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nshosts",
                        to="checks.mailtestrpki",
                    ),
                ),
                (
                    "webtestrpki",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nshosts",
                        to="checks.webtestrpki",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RpkiMxNsHost",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("host", models.CharField(max_length=255)),
                ("score", models.IntegerField(null=True)),
                ("routing", checks.models.ListField(default={})),
                (
                    "mailtestrpki",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mxnshosts",
                        to="checks.mailtestrpki",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RpkiMxHost",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("host", models.CharField(max_length=255)),
                ("score", models.IntegerField(null=True)),
                ("routing", checks.models.ListField(default={})),
                (
                    "mailtestrpki",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mxhosts",
                        to="checks.mailtestrpki",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="batchmailtest",
            name="rpki",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="checks.mailtestrpki"),
        ),
        migrations.AddField(
            model_name="batchwebtest",
            name="rpki",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="checks.webtestrpki"),
        ),
        migrations.AddField(
            model_name="domaintestreport",
            name="rpki",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="checks.webtestrpki"),
        ),
        migrations.AddField(
            model_name="mailtestreport",
            name="rpki",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="checks.mailtestrpki"),
        ),
    ]
