# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-17 09:14
from __future__ import unicode_literals

import checks.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0008_django_upgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTestRpki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('domain', models.CharField(default='', max_length=255)),
                ('report', checks.models.ListField(default='')),
                ('mail_score', models.IntegerField(null=True)),
                ('ns_score', models.IntegerField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('max_score', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RpkiMxDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('score', models.IntegerField(null=True)),
                ('routing', checks.models.ListField(default={})),
                ('mailtestrpki', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mxdomains', to='checks.MailTestRpki')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RpkiNsDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('score', models.IntegerField(null=True)),
                ('routing', checks.models.ListField(default={})),
                ('mailtestrpki', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nsdomains', to='checks.MailTestRpki')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RpkiWebDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('score', models.IntegerField(null=True)),
                ('routing', checks.models.ListField(default={})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebTestRpki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('domain', models.CharField(default='', max_length=255)),
                ('report', checks.models.ListField(default='')),
                ('web_score', models.IntegerField(null=True)),
                ('ns_score', models.IntegerField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('max_score', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='batchwebtest',
            name='rpki_errors',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batchwebtest',
            name='rpki_status',
            field=enumfields.fields.EnumIntegerField(default=0, enum=checks.models.BatchTestStatus),
        ),
        migrations.AddField(
            model_name='rpkiwebdomain',
            name='webtestrpki',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webdomains', to='checks.WebTestRpki'),
        ),
        migrations.AddField(
            model_name='rpkinsdomain',
            name='webtestrpki',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nsdomains', to='checks.WebTestRpki'),
        ),
        migrations.AddField(
            model_name='batchwebtest',
            name='rpki',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checks.WebTestRpki'),
        ),
        migrations.AddField(
            model_name='domaintestreport',
            name='rpki',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checks.WebTestRpki'),
        ),
        migrations.AddField(
            model_name='mailtestreport',
            name='rpki',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checks.MailTestRpki'),
        ),
    ]
