# Generated by Django 3.2.5 on 2021-11-29 10:59

import checks.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0010_rpki_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='RpkiMxNsDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('score', models.IntegerField(null=True)),
                ('routing', checks.models.ListField(default={})),
                ('mailtestrpki', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mxnsdomains', to='checks.mailtestrpki')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
