# Generated by Django 3.2.18 on 2023-02-15 14:21

import checks.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0010_add_securitytxt"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaintestappsecpriv",
            name="content_security_policy_errors",
            field=checks.models.ListField(default=[]),
        ),
    ]
