# Generated by Django 3.2.18 on 2023-05-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0011_domaintestappsecpriv_content_security_policy_errors"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="domaintestipv6",
            index=models.Index(fields=["domain", "-id"], name="checks_domaintestipv6_dom_idx"),
        ),
        migrations.AddIndex(
            model_name="mailtestipv6",
            index=models.Index(fields=["domain", "-id"], name="checks_mailtestipv6_domain_idx"),
        ),
    ]
