# Generated by Django 3.2.18 on 2023-05-04 23:00
# Fixes #966

from django.db import migrations, models


class Migration(migrations.Migration):
    # Concurrent index creation happens outside of a transaction.
    atomic = False

    dependencies = [
        ("checks", "0011_domaintestappsecpriv_content_security_policy_errors"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'CREATE INDEX CONCURRENTLY IF NOT EXISTS "checks_domaintestipv6_dom_idx" ON "checks_domaintestipv6" ("domain", "id" DESC);',
                'CREATE INDEX CONCURRENTLY IF NOT EXISTS "checks_mailtestipv6_domain_idx" ON "checks_mailtestipv6" ("domain", "id" DESC);',
            ],
            reverse_sql=[
                'DROP INDEX CONCURRENTLY IF EXISTS "checks_domaintestipv6_dom_idx";',
                'DROP INDEX CONCURRENTLY IF EXISTS "checks_mailtestipv6_domain_idx";',
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="domaintestipv6",
                    index=models.Index(fields=["domain", "-id"], name="checks_domaintestipv6_dom_idx"),
                ),
                migrations.AddIndex(
                    model_name="mailtestipv6",
                    index=models.Index(fields=["domain", "-id"], name="checks_mailtestipv6_domain_idx"),
                ),
            ],
        ),
    ]
