# Generated by Django 3.2.12 on 2022-06-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0011_rpkimxnsdomain"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RpkiMxDomain",
            new_name="RpkiMxHost",
        ),
        migrations.RenameModel(
            old_name="RpkiMxNsDomain",
            new_name="RpkiMxNsHost",
        ),
        migrations.RenameModel(
            old_name="RpkiNsDomain",
            new_name="RpkiNsHost",
        ),
        migrations.RenameModel(
            old_name="RpkiWebDomain",
            new_name="RpkiWebHost",
        ),
        migrations.RenameField(
            model_name="rpkimxhost",
            old_name="domain",
            new_name="host",
        ),
        migrations.RenameField(
            model_name="rpkimxnshost",
            old_name="domain",
            new_name="host",
        ),
        migrations.RenameField(
            model_name="rpkinshost",
            old_name="domain",
            new_name="host",
        ),
        migrations.RenameField(
            model_name="rpkiwebhost",
            old_name="domain",
            new_name="host",
        ),
    ]
