# Generated by Django 3.2.12 on 2022-06-21 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0012_rpki_name_change"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rpkimxhost",
            name="mailtestrpki",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="mxhosts", to="checks.mailtestrpki"
            ),
        ),
        migrations.AlterField(
            model_name="rpkimxnshost",
            name="mailtestrpki",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mxnshosts",
                to="checks.mailtestrpki",
            ),
        ),
        migrations.AlterField(
            model_name="rpkinshost",
            name="mailtestrpki",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="nshosts", to="checks.mailtestrpki"
            ),
        ),
        migrations.AlterField(
            model_name="rpkinshost",
            name="webtestrpki",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="nshosts", to="checks.webtestrpki"
            ),
        ),
        migrations.AlterField(
            model_name="rpkiwebhost",
            name="webtestrpki",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="webhosts", to="checks.webtestrpki"
            ),
        ),
    ]
