# Generated by Django 3.2.18 on 2023-05-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0012_domain_index_performance_non_existing_domains"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="domaintestappsecpriv",
            index=models.Index(fields=["domain", "-id"], name="checks_domtstappsec_dom_idx"),
        ),
        migrations.AddIndex(
            model_name="domaintestdnssec",
            index=models.Index(fields=["domain", "-id"], name="checks_domtestdnssec_dom_idx"),
        ),
        migrations.AddIndex(
            model_name="mailtestauth",
            index=models.Index(fields=["domain", "-id"], name="checks_mailtestauth_dom_idx"),
        ),
        migrations.AddIndex(
            model_name="mailtestdnssec",
            index=models.Index(fields=["domain", "-id"], name="checks_mailtestdnssec_dom_idx"),
        ),
        migrations.AddIndex(
            model_name="mailtestrpki",
            index=models.Index(fields=["domain", "-id"], name="checks_mailtestrpki_dom_idx"),
        ),
        migrations.AddIndex(
            model_name="mailtesttls",
            index=models.Index(fields=["domain", "-id"], name="checks_mailtesttls_dom_idx"),
        ),
        migrations.AddIndex(
            model_name="webtestrpki",
            index=models.Index(fields=["domain", "-id"], name="checks_webtestrpki_dom_idx"),
        ),
        migrations.AddIndex(
            model_name="webtesttls",
            index=models.Index(fields=["domain", "-id"], name="checks_webtesttls_dom_idx"),
        ),
    ]
