# Generated by Django 3.2.23 on 2024-02-12 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0014_auto_20230804_0855"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchuser",
            name="email",
        ),
        migrations.RemoveField(
            model_name="batchuser",
            name="name",
        ),
        migrations.RemoveField(
            model_name="batchuser",
            name="organization",
        ),
    ]
