# Generated by Django 3.2.19 on 2023-06-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0015_auto_20240212_1616"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailtestrpki",
            name="mail_score",
        ),
        migrations.RemoveField(
            model_name="mailtestrpki",
            name="ns_score",
        ),
        migrations.RemoveField(
            model_name="webtestrpki",
            name="ns_score",
        ),
        migrations.RemoveField(
            model_name="webtestrpki",
            name="web_score",
        ),
        migrations.AddField(
            model_name="mailtestrpki",
            name="mail_exists_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="mailtestrpki",
            name="mail_valid_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="mailtestrpki",
            name="mx_ns_exists_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="mailtestrpki",
            name="mx_ns_valid_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="mailtestrpki",
            name="ns_exists_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="mailtestrpki",
            name="ns_valid_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="webtestrpki",
            name="ns_exists_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="webtestrpki",
            name="ns_valid_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="webtestrpki",
            name="web_exists_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="webtestrpki",
            name="web_valid_score",
            field=models.IntegerField(null=True),
        ),
    ]
