# AddField Generated by Django 3.2.24 on 2024-03-09 12:49
# Manually created SQL migration to handle old reports

from django.db import migrations  # , models


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0015_auto_20240212_1616"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='domaintestappsecpriv',
        #     name='securitytxt_found_url',
        #     field=models.CharField(max_length=8000, null=True),
        # ),
        migrations.RunSQL(
            sql=[
                "ALTER TABLE checks_domaintestappsecpriv ADD COLUMN securitytxt_found_url VARCHAR(8000);",
                "UPDATE checks_domaintestappsecpriv SET securitytxt_found_url=securitytxt_found_host WHERE securitytxt_enabled;",
            ],
            reverse_sql=[
                "ALTER TABLE checks_domaintestappsecpriv DROP COLUMN securitytxt_found_url;",
            ],
        ),
    ]
