# Generated by Django 4.2.15 on 2024-11-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0015_add_rpki_scoring"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaintesttls",
            name="redirect_domain",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
