# Generated by Django 4.2.16 on 2024-12-03 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0015_add_rpki_scoring"),
    ]

    operations = [
        migrations.AddField(
            model_name="webtestappsecpriv",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="webtesttls",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
