# Generated by Django 4.2.16 on 2025-01-20 16:13

import checks.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0016_webtestappsecpriv_timestamp_webtesttls_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaintesttls",
            name="cert_caa_record",
            field=checks.models.ListField(default=[]),
        ),
        migrations.AddField(
            model_name="domaintesttls",
            name="cert_caa_score",
            field=models.IntegerField(null=True),
        ),
    ]
