# Generated by Django 4.2.20 on 2025-04-07 13:51

import checks.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0017_domaintesttls_caa_enabled_domaintesttls_caa_errors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaintesttls",
            name="caa_records",
            field=checks.models.ListField(default=[]),
        ),
    ]
