# Generated by Django 4.2.22 on 2025-07-22 18:17
from enum import Enum

import checks.models
from django.db import migrations
import enumfields.fields


class TLSClientInitiatedRenegotiationStatus(Enum):
    not_allowed = 1
    allowed_with_low_limit = 2
    allowed_with_too_high_limit = 3


def set_client_reneg_new(apps, schema_editor):
    DomainTestTls = apps.get_model("checks", "DomainTestTls")
    DomainTestTls.objects.update(client_reneg_new=TLSClientInitiatedRenegotiationStatus.not_allowed.value)
    DomainTestTls.objects.filter(client_reneg=True).update(
        client_reneg_new=TLSClientInitiatedRenegotiationStatus.allowed_with_too_high_limit.value
    )


def set_client_reneg_old(apps, schema_editor):
    DomainTestTls = apps.get_model("checks", "DomainTestTls")
    DomainTestTls.objects.update(client_reneg=False)
    DomainTestTls.objects.filter(
        client_reneg_new=TLSClientInitiatedRenegotiationStatus.allowed_with_too_high_limit.value
    ).update(client_reneg=True)


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0018_domaintesttls_caa_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaintesttls",
            name="client_reneg_new",
            field=enumfields.fields.EnumField(
                enum=checks.models.TLSClientInitiatedRenegotiationStatus,
                max_length=10,
                null=True,
            ),
        ),
        migrations.RunPython(set_client_reneg_new, set_client_reneg_old),
        migrations.RemoveField(
            model_name="domaintesttls",
            name="client_reneg",
        ),
        migrations.RenameField(
            model_name="domaintesttls",
            old_name="client_reneg_new",
            new_name="client_reneg",
        ),
    ]
