import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0018_domaintesttls_caa_records"),
    ]

    operations = [
        # Note db_index is False on the ForeignKey to prevent extra indices that are not needed
        migrations.CreateModel(
            name="Fame",
            fields=[
                ("id", models.IntegerField()),
                ("domain", models.CharField(max_length=255, primary_key=True)),
                (
                    "site_report",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checks.domaintestreport",
                        db_index=False,
                    ),
                ),
                ("site_report_timestamp", models.DateTimeField(null=True)),
                (
                    "mail_report",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checks.mailtestreport",
                        db_index=False,
                    ),
                ),
                ("mail_report_timestamp", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        # AutoField has to be primary key in Django, to solve this manually alter SQL this field
        # see https://github.com/django/django/blob/787f3130f751283140fe2be8188eb5299552232d/django/db/models/fields/__init__.py#L2801
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "checks_fame" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;',
                """
CREATE OR REPLACE FUNCTION fn_update_site_fame()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.score IS NULL THEN
    -- NOOP
  ELSIF NEW.score = 100 THEN
    INSERT INTO checks_fame (domain, site_report_id, site_report_timestamp, mail_report_id, mail_report_timestamp)
    VALUES (NEW.domain, NEW.id, NEW.timestamp, NULL, NULL)
    ON CONFLICT (domain)
    DO UPDATE SET site_report_id = NEW.id, site_report_timestamp = NEW.timestamp;
  ELSE
    DELETE FROM checks_fame WHERE domain = NEW.domain AND mail_report_id IS NULL;
    UPDATE checks_fame SET site_report_id = NULL, site_report_timestamp = NULL WHERE domain = NEW.domain;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
""",
                """
CREATE OR REPLACE FUNCTION fn_update_mail_fame()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.score IS NULL THEN
    -- NOOP
  ELSIF NEW.score = 100 THEN
    INSERT INTO checks_fame (domain, site_report_id, site_report_timestamp, mail_report_id, mail_report_timestamp)
      VALUES (NEW.domain, NULL, NULL, NEW.id, NEW.timestamp)
    ON CONFLICT (domain)
    DO UPDATE SET mail_report_id = NEW.id, mail_report_timestamp = NEW.timestamp;
  ELSE
    DELETE FROM checks_fame WHERE domain = NEW.domain AND site_report_id IS NULL;
    UPDATE checks_fame SET mail_report_id = NULL, mail_report_timestamp = NULL WHERE domain = NEW.domain;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
""",
                """
CREATE TRIGGER tr_update_site_fame
  AFTER INSERT OR UPDATE ON checks_domaintestreport
  FOR EACH ROW EXECUTE PROCEDURE fn_update_site_fame();
""",
                """
CREATE TRIGGER tr_update_mail_fame
  AFTER INSERT OR UPDATE ON checks_mailtestreport
  FOR EACH ROW EXECUTE PROCEDURE fn_update_mail_fame();
""",
                """
WITH
  site_fame AS (
    SELECT domain, id AS site_report_id, timestamp AS site_report_timestamp FROM (
      SELECT domain, score, id, timestamp, rank() OVER (PARTITION BY domain ORDER BY id DESC) FROM checks_domaintestreport
    ) alias WHERE rank = 1 AND score = 100),
  mail_fame AS (
    SELECT domain, id AS mail_report_id, timestamp AS mail_report_timestamp  FROM (
      SELECT domain, score, id, timestamp, rank() OVER (PARTITION BY domain ORDER BY id DESC) FROM checks_mailtestreport
    ) alias WHERE rank = 1 AND score = 100)
INSERT INTO checks_fame (domain, site_report_id, site_report_timestamp, mail_report_id, mail_report_timestamp)
  SELECT * FROM site_fame FULL OUTER JOIN mail_fame USING (domain);
""",
            ],
            reverse_sql=[
                'ALTER TABLE "checks_fame" ALTER COLUMN "id" DROP IDENTITY;',
                'DROP TRIGGER IF EXISTS "tr_update_mail_fame" ON "checks_mailtestreport";',
                'DROP TRIGGER IF EXISTS "tr_update_site_fame" ON "checks_domaintestreport";',
                'DROP FUNCTION IF EXISTS "fn_update_mail_fame";',
                'DROP FUNCTION IF EXISTS "fn_update_site_fame";',
                'DELETE FROM "checks_fame";',
            ],
            state_operations=[
                migrations.AlterField(
                    "Fame",
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                migrations.AlterField("Fame", "domain", models.CharField(max_length=255)),
            ],
        ),
    ]
