# Generated by Django 4.2.22 on 2025-08-12 12:28

import checks.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0019_domaintesttls_client_reneg_to_enum"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaintesttls",
            name="extended_master_secret",
            field=enumfields.fields.EnumField(
                default=3,
                enum=checks.models.TLSExtendedMasterSecretStatus,
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="domaintesttls",
            name="extended_master_secret_score",
            field=models.IntegerField(null=True),
        ),
    ]
