# Generated by Django 4.2.22 on 2025-07-22 18:17
from enum import Enum

import checks.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0019_domaintesttls_client_reneg_to_enum"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domaintesttls",
            name="client_reneg_old",
        ),
    ]
