{
 "title": "Celery / Tasks",
 "description": "A dashboard that monitors Celery. It is created using the Celery-mixin for the the (Celery-exporter)[https://github.com/danihodovic/celery-exporter]",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "task",
    "query": "label_values(celery_task_sent_total, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Celery Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(celery_worker_up{job=~\"celery|celery_exporter\"} == 1)"
    }
   ]
  },
  {
   "title": "Tasks Active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(celery_worker_tasks_active{job=~\"celery|celery_exporter\"})"
    }
   ]
  },
  {
   "title": "Tasks received by workers last 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(celery_task_received_total{job=~\"celery|celery_exporter\"}[1d])))\n"
    }
   ]
  },
  {
   "title": "Successful completion rate last 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(celery_task_succeeded_total{job=~\"celery|celery_exporter\"}[1d])))\n/(sum(round(increase(celery_task_succeeded_total{job=~\"celery|celery_exporter\"}[1d])))\n+sum(round(increase(celery_task_failed_total{job=~\"celery|celery_exporter\"}[1d])))\n)\n"
    }
   ]
  },
  {
   "title": "Average Runtime for Tasks last 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(celery_task_runtime_sum{job=~\"celery|celery_exporter\"}[1d])) / sum(rate(celery_task_runtime_count{job=~\"celery|celery_exporter\"}[1d])) > 0\n"
    }
   ]
  },
  {
   "title": "Top 5 failed tasks last 24h",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "round(topk(5, sum by (name) (increase(celery_task_failed_total{job=~\"celery|celery_exporter\"}[1d]) > 0 )))\n"
    }
   ]
  },
  {
   "title": "Top 5 exceptions last 24h",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "round(topk(5, sum by (exception) (increase(celery_task_failed_total{job=~\"celery|celery_exporter\"}[1d]) > 0 )))\n"
    }
   ]
  },
  {
   "title": "Top 5 task runtime last 24h",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "topk(5, (sum by(name) (rate(celery_task_runtime_sum{job=~\"celery|celery_exporter\"}[1d])) / sum by (name) (rate(celery_task_runtime_count{job=~\"celery|celery_exporter\"}[1d])) > 0 ))\n"
    }
   ]
  },
  {
   "title": "Individual Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Task Stats",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (name) (round(increase(celery_task_succeeded_total{job=~\"celery|celery_exporter\", name=~\"$task\"}[$__range])))\n/(sum by (name) (round(increase(celery_task_succeeded_total{job=~\"celery|celery_exporter\", name=~\"$task\"}[$__range])))\n+sum by (name) (round(increase(celery_task_failed_total{job=~\"celery|celery_exporter\", name=~\"$task\"}[$__range])))\n) > -1\n"
    },
    {
     "expr": "sum by (name) (round(increase(celery_task_received_total{job=~\"celery|celery_exporter\", name=~\"$task\"}[$__range]))) > 0\n"
    },
    {
     "expr": "sum by (name) (round(increase(celery_task_succeeded_total{job=~\"celery|celery_exporter\", name=~\"$task\"}[$__range]))) > 0\n"
    },
    {
     "expr": "sum by (name) (round(increase(celery_task_failed_total{job=~\"celery|celery_exporter\", name=~\"$task\"}[$__range]))) > 0\n"
    },
    {
     "expr": "sum by (name) (round(increase(celery_task_rejected_total{job=~\"celery|celery_exporter\", name=~\"$task\"}[$__range]))) > 0\n"
    },
    {
     "expr": "sum by (name) (round(increase(celery_task_retried_total{job=~\"celery|celery_exporter\", name=~\"$task\"}[$__range]))) > 0\n"
    },
    {
     "expr": "sum by (name) (round(increase(celery_task_revoked_total{job=~\"celery|celery_exporter\", name=~\"$task\"}[$__range]))) > 0\n"
    }
   ]
  },
  {
   "title": "Tasks completed with 10m intervals",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (round(increase(celery_task_succeeded_total{job=~\"celery|celery_exporter\", name=~\"$task\"}[10m])))\n",
     "legendFormat": "Succeeded - {{ name }}"
    },
    {
     "expr": "sum by (name) (round(increase(celery_task_failed_total{job=~\"celery|celery_exporter\", name=~\"$task\"}[10m])))\n",
     "legendFormat": "Failed - {{ name }}"
    },
    {
     "expr": "sum by (name) (round(increase(celery_task_received_total{job=~\"celery|celery_exporter\", name=~\"$task\"}[10m])))\n",
     "legendFormat": "Received - {{ name }}"
    },
    {
     "expr": "sum by (name) (round(increase(celery_task_retried_total{job=~\"celery|celery_exporter\", name=~\"$task\"}[10m])))\n",
     "legendFormat": "Retried - {{ name }}"
    },
    {
     "expr": "sum by (name) (round(increase(celery_task_rejected_total{job=~\"celery|celery_exporter\", name=~\"$task\"}[10m])))\n",
     "legendFormat": "Rejected - {{ name }}"
    },
    {
     "expr": "sum by (name) (round(increase(celery_task_revoked_total{job=~\"celery|celery_exporter\", name=~\"$task\"}[10m])))\n",
     "legendFormat": "Revoked - {{ name }}"
    }
   ]
  },
  {
   "title": "Tasks Runtime with 10m intervals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(celery_task_runtime_sum{job=~\"celery|celery_exporter\", name=~\"$task\"}[10m])) / sum by (name) (rate(celery_task_runtime_count{job=~\"celery|celery_exporter\", name=~\"$task\"}[10m])) > 0\n",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}