$ORIGIN nlnetlabs.tk.
$TTL 60
@     IN     SOA    ns2a.tk. admin.nlnetlabs.tk. (
              1      ; serial
              5S     ; refresh (5 seconds)
              1S     ; retry (1 seconds)
             15S     ; expire (15 seconds)
              5S     ; minimum (5 seconds)
                    )
@     IN     NS     ns2a.tk.
@     IN     NS     ns2b.tk.
test  IN     NS     ns2a.tk.
test  IN     NS     ns2b.tk.
