$ORIGIN test.nlnetlabs.tk.
$TTL 60
@                                         IN	 SOA    ns2a.tk. admin.nlnetlabs.tk. (
                                              1      ; serial
                                              5S     ; refresh (5 seconds)
                                              1S     ; retry (1 seconds)
                                              15S    ; expire (15 seconds)
                                              5S     ; minimum (5 seconds)
                                          )
@                                         IN  NS     ns2a.tk.
@                                         IN  NS     ns2b.tk.
internetnl                                IN  A      {{APP_IP}}
internetnl                                IN  AAAA   {{APP_IPV6}}
en.internetnl                             IN  A      {{APP_IP}}
en.internetnl                             IN  AAAA   {{APP_IPV6}}
nl.internetnl                             IN  A      {{APP_IP}}
nl.internetnl                             IN  AAAA   {{APP_IPV6}}
ca-ocsp                                   IN  A      {{TARGET_CA_OCSP_IP}}
ca-ocsp                                   IN  AAAA   {{TARGET_CA_OCSP_IPV6}}
tls1213                                   IN  A      {{TARGET_TLS1213_IP}}
tls1213                                   IN  AAAA   {{TARGET_TLS1213_IPV6}}
tls1213ipv4only                           IN  A      {{TARGET_TLS1213_IP}}
tls1213sni                                IN  A      {{TARGET_TLS1213_IP}}
tls1213sni                                IN  AAAA   {{TARGET_TLS1213_IPV6}}
tls1213nohsts                             IN  A      {{TARGET_TLS1213_IP}}
tls1213nohsts                             IN  AAAA   {{TARGET_TLS1213_IPV6}}
tls1213shorthsts                          IN  A      {{TARGET_TLS1213_IP}}
tls1213shorthsts                          IN  AAAA   {{TARGET_TLS1213_IPV6}}
tls1213wrongcertname                      IN  A      {{TARGET_TLS1213_IP}}
tls1213wrongcertname                      IN  AAAA   {{TARGET_TLS1213_IPV6}}
tls1213defaultvhost                       IN  A      {{TARGET_TLS1213_IP}}
tls1213defaultvhost                       IN  AAAA   {{TARGET_TLS1213_IPV6}}
tls1213noocspstaple                       IN  A      {{TARGET_TLS1213_IP}}
tls1213noocspstaple                       IN  AAAA   {{TARGET_TLS1213_IPV6}}
tls1213nosha2                             IN  A      {{TARGET_TLS1213_IP}}
tls1213nosha2                             IN  AAAA   {{TARGET_TLS1213_IPV6}}
tls1213tlscompression                     IN  A      {{TARGET_TLS1213TLSCOMPRESSION_IP}}
tls1213tlscompression                     IN  AAAA   {{TARGET_TLS1213TLSCOMPRESSION_IPV6}}
tls10only                                 IN  A      {{TARGET_TLS10ONLY_IP}}
tls10only                                 IN  AAAA   {{TARGET_TLS10ONLY_IPV6}}
tls10onlyhonorclientcipherorder           IN  A      {{TARGET_TLS10ONLYCLIENTCIPHERORDER_IP}}
tls10onlyhonorclientcipherorder           IN  AAAA   {{TARGET_TLS10ONLYCLIENTCIPHERORDER_IPV6}}
tls10onlyinsecurereneg                    IN  A      {{TARGET_TLS10ONLYINSECURERENEG_IP}}
tls10onlyinsecurereneg                    IN  AAAA   {{TARGET_TLS10ONLYINSECURERENEG_IPV6}}
tls11only                                 IN  A      {{TARGET_TLS11ONLY_IP}}
tls11only                                 IN  AAAA   {{TARGET_TLS11ONLY_IPV6}}
tls1011                                   IN  A      {{TARGET_TLS1011_IP}}
tls1011                                   IN  AAAA   {{TARGET_TLS1011_IPV6}}
tls1112                                   IN  A      {{TARGET_TLS1112_IP}}
tls1112                                   IN  AAAA   {{TARGET_TLS1112_IPV6}}
tls12only                                 IN  A      {{TARGET_TLS12ONLY_IP}}
tls12only                                 IN  AAAA   {{TARGET_TLS12ONLY_IPV6}}
tls12only                                 IN  MX     10   mailtest
tls12onlyffdhe2048                        IN  A      {{TARGET_TLS12ONLY_IP}}
tls12onlyffdhe2048                        IN  AAAA   {{TARGET_TLS12ONLY_IPV6}}
tls12onlyffdhe3072                        IN  A      {{TARGET_TLS12ONLY_IP}}
tls12onlyffdhe3072                        IN  AAAA   {{TARGET_TLS12ONLY_IPV6}}
tls12onlyffother                          IN  A      {{TARGET_TLS12ONLY_IP}}
tls12onlyffother                          IN  AAAA   {{TARGET_TLS12ONLY_IPV6}}
tls12onlylegacybadciphers                 IN  A      {{TARGET_TLS12ONLYLEGACYBADCIPHERS_IP}}
tls12onlylegacybadciphers                 IN  AAAA   {{TARGET_TLS12ONLYLEGACYBADCIPHERS_IPV6}}
tls12onlymodernbadciphers                 IN  A      {{TARGET_TLS12ONLYMODERNBADCIPHERS_IP}}
tls12onlymodernbadciphers                 IN  AAAA   {{TARGET_TLS12ONLYMODERNBADCIPHERS_IPV6}}
tls12onlylegacyphaseoutciphers            IN  A      {{TARGET_TLS12ONLYLEGACYPHASEOUTCIPHERS_IP}}
tls12onlylegacyphaseoutciphers            IN  AAAA   {{TARGET_TLS12ONLYLEGACYPHASEOUTCIPHERS_IPV6}}
tls12onlymodernphaseoutciphers            IN  A      {{TARGET_TLS12ONLYMODERNPHASEOUTCIPHERS_IP}}
tls12onlymodernphaseoutciphers            IN  AAAA   {{TARGET_TLS12ONLYMODERNPHASEOUTCIPHERS_IPV6}}
tls13only                                 IN  A      {{TARGET_TLS13ONLY_IP}}
tls13only                                 IN  AAAA   {{TARGET_TLS13ONLY_IPV6}}
tls13onlydiffipv4ipv6                     IN  A      {{TARGET_TLS13ONLYDIFFIPV4IPV6_IP}}
tls13onlydiffipv4ipv6                     IN  AAAA   {{TARGET_TLS13ONLYDIFFIPV4IPV6_IPV6}}
tls130rtt                                 IN  A      {{TARGET_TLS130RTT_IP}}
tls130rtt                                 IN  AAAA   {{TARGET_TLS130RTT_IPV6}}
tls13invalidocsp                          IN  A      {{TARGET_TLS13INVALIDOCSP_IP}}
tls13invalidocsp                          IN  AAAA   {{TARGET_TLS13INVALIDOCSP_IPV6}}
tls13onlyhonorclientcipherorder           IN  A      {{TARGET_TLS13ONLYCLIENTCIPHERORDER_IP}}
tls13onlyhonorclientcipherorder           IN  AAAA   {{TARGET_TLS13ONLYCLIENTCIPHERORDER_IPV6}}
ssl2only                                  IN  A      {{TARGET_SSL2ONLY_IP}}
ssl2only                                  IN  AAAA   {{TARGET_SSL2ONLY_IPV6}}
ssl3only                                  IN  A      {{TARGET_SSL3ONLY_IP}}
ssl3only                                  IN  AAAA   {{TARGET_SSL3ONLY_IPV6}}
nossl                                     IN  A      {{TARGET_NOSSL_IP}}
nossl                                     IN  AAAA   {{TARGET_NOSSL_IPV6}}
mailtest                                  IN  A      {{TARGET_TLS12ONLY_IP}}
mailtest                                  IN  AAAA   {{TARGET_TLS12ONLY_IPV6}}

; TLSA records generated using https://www.huque.com/bin/gen_tlsa
; using options: port=443 transport=tcp domain=tls1213
; pem=docker/it/targetbase/certs/wildcard.test.nlnetlabs.tk.crt (for example)
_443._tcp.tls1213                         IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls1213ipv4only                 IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls1213sni                      IN  TLSA   3 1 1 8d0b8af3cfe3dc53375b632b65b1f8864c7afbea15a85622f7a8aa1386d2048d
_443._tcp.tls1213nohsts                   IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls1213shorthsts                IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls1213noocspstaple             IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls1213nosha2                   IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls1213tlscompression           IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls10only                       IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls10onlyhonorclientcipherorder IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls10onlyinsecurereneg          IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls11only                       IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls1011                         IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls1112                         IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls12only                       IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls12onlyffdhe3072              IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls12onlyffdhe2048              IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls12onlyffother                IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls12onlylegacybadciphers       IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls12onlymodernbadciphers       IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls12onlylegacyphaseoutciphers  IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls12onlymodernphaseoutciphers  IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls13onlydiffipv4ipv6           IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls13only                       IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls130rtt                       IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls13invalidocsp                IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.tls13onlyhonorclientcipherorder IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.ssl2only                        IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.ssl3only                        IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
_443._tcp.nossl                           IN  TLSA   3 1 1 f58f7492351360e3855bcd064f545cbc365df7518dab2c7a4b843ec3b449af5c
